### ISSUE TITLE
Cryptic panic message if schema.json was not found

### ISSUE THREAD

**Issue by iyesin** [bayard-search/bayard#7]
Expected result:
```
Can't find scheme.json. Default location (`./etc/schema.json`) could be overridden with `-s, --schema-file` command-line paramethers
```

Actual result:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by mosuka** [comment]
@iyesin 
Sorry for the inconvenience. The error message output will be improved in the future.
Thanks,

**Comment by barrotsteindev** [comment]
Is this still relevant? @iyesin

**Comment by iyesin** [comment]
@barrotsteindev yes, it is.
I just invoked `$ cargo install bayard --version 0.8.5`. It finished installation.
So I have most recently released version of bayard:
```
$ bayard --version
bayard 0.8.5
```

Now, invoking just `bayard` command gives me almost the same panic message:
```
$ bayard 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bayard-0.8.5/src/main.rs:139:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by mosuka** [comment]
@barrotsteindev 
Merged #121.
Thank you for your contribution.
